---
- name: Gather facts for ITS Install
  ansible.builtin.setup:

- name: Get the username of the user running the playbook
  set_fact:
    playbook_user: "{{ ansible_env.USER }}"

- name: Download ITS Platform
  get_url:
    url: https://prod.setup.itsupport247.net/linux/BareboneAgent/64/Appliances_Linux_Server_ITSPlatform_TKNaf3e3f02-0b91-4a47-8657-65533f0cf973/RUN/setup
    dest: /tmp/Appliances_Linux_Server_ITSPlatform_TKNaf3e3f02-0b91-4a47-8657-65533f0cf973.run
    owner: root
    group: root
    mode: 0755
  become: true
  become_method: sudo

- name: Channge ITS Platform permissions
  shell: chmod 777 /tmp/Appliances_Linux_Server_ITSPlatform_TKNaf3e3f02-0b91-4a47-8657-65533f0cf973.run
  become: true
  become_method: sudo

- name: Check if the process is running
  shell: pgrep -f "ITS247MSMACTL"
  register: process_check
  ignore_errors: true

- name: Debug the output of process_check
  debug:
    msg: "Process check output: {{ process_check }}"

- name: Check if the process is running 11111111
  shell: pgrep -f "1ITS1247M1SMACTL"
  register: process_check1
  ignore_errors: true

- name: Debug the output of process_check 11111111
  debug:
    msg: "Process check output: {{ process_check1 }}"

- name: Installing ITS Platform permissions
  shell: /bin/bash /tmp/Appliances_Linux_Server_ITSPlatform_TKNaf3e3f02-0b91-4a47-8657-65533f0cf973.run
  become: true
  become_method: sudo
  when: process_check.rc = 0 or process_check.stdout == ""

- name: Removing temporary ITS files
  shell: "rm /tmp/Appliances_Linux_Server_ITSPlatform_TKNaf3e3f02-0b91-4a47-8657-65533f0cf973.run"
  become: true
  become_method: sudo
  ignore_errors: yes