---
- name: Gather facts for ITS Install
  ansible.builtin.setup:

- name: Get the username of the user running the playbook
  set_fact:
    playbook_user: "{{ ansible_env.USER }}"

- name: Download ITS Platform
  get_url:
    url: https://prod.setup.itsupport247.net/linux/BareboneAgent/64/Appliances_Linux_Server_ITSPlatform_TKNaf3e3f02-0b91-4a47-8657-65533f0cf973/RUN/setup
    dest: /tmp/Appliances_Linux_Server_ITSPlatform_TKNaf3e3f02-0b91-4a47-8657-65533f0cf973.run
    owner: root
    group: root
    mode: 0755
  become: true
  become_method: sudo

- name: Channge ITS Platform permissions
  shell: chmod 777 /tmp/Appliances_Linux_Server_ITSPlatform_TKNaf3e3f02-0b91-4a47-8657-65533f0cf973.run
  become: true
  become_method: sudo

- name: Installing ITS Platform permissions
  shell: /bin/bash /tmp/Appliances_Linux_Server_ITSPlatform_TKNaf3e3f02-0b91-4a47-8657-65533f0cf973.run
  become: true
  become_method: sudo

- name: Removing temporary java files
  shell: "rm /tmp/Appliances_Linux_Server_ITSPlatform_TKNaf3e3f02-0b91-4a47-8657-65533f0cf973.run"
  become: true
  become_method: sudo
  ignore_errors: yes

- name: "Adding user {{ playbook_user }} to group ssl-cert"
  user:
    name: "{{ playbook_user }}"
    groups: ssl-cert
    append: yes