---
- name: Gather facts for ITS Install
  ansible.builtin.setup:

- name: Get the username of the user running the playbook
  set_fact:
    playbook_user: "{{ ansible_env.USER }}"

- name: Check if ITS service is running
  tasks: 
    - name: Gather info for services
      service_facts:

- name: Download ITS Platform
  get_url:
    url: https://prod.setup.itsupport247.net/linux/BareboneAgent/64/Appliances_Linux_Server_ITSPlatform_TKNaf3e3f02-0b91-4a47-8657-65533f0cf973/RUN/setup
    dest: /tmp/Appliances_Linux_Server_ITSPlatform_TKNaf3e3f02-0b91-4a47-8657-65533f0cf973.run
    owner: root
    group: root
    mode: 0755
  become: true
  become_method: sudo

- name: Channge ITS Platform permissions
  shell: chmod 777 /tmp/Appliances_Linux_Server_ITSPlatform_TKNaf3e3f02-0b91-4a47-8657-65533f0cf973.run
  become: true
  become_method: sudo

- name: Debug the output of service_facts
  debug:
    msg: "{{ ansible.facts.services['ITSPlatform.service'] }}"

- name: Installing ITS Platform permissions
  shell: /bin/bash /tmp/Appliances_Linux_Server_ITSPlatform_TKNaf3e3f02-0b91-4a47-8657-65533f0cf973.run
  become: true
  become_method: sudo
  when: ansible.facts.services['ITSPlatform.service'].state != 'running'

- name: Removing temporary ITS files
  shell: "rm /tmp/Appliances_Linux_Server_ITSPlatform_TKNaf3e3f02-0b91-4a47-8657-65533f0cf973.run"
  become: true
  become_method: sudo
  ignore_errors: yes