---
- name: Include a list of tasks dynamically
  include_tasks: 
    file: "{{ item }}"
  loop:
    - apt-stuff.yml
    - install-slapd.yml
    - install-pwsh.yml
    - install-java.yml
    - go-stuff.yml
    - github-repos.yml
    - python-tools.yml
    - gem-tools.yml
