---
- name: Include a list of tasks dynamically
  include_tasks: apt-stuff.yml
  include_tasks: install-slapd.yml
  include_tasks: install-ITS.yml
  include_tasks: install-pwsh.yml
  include_tasks: install-java.yml
  include_tasks: go-stuff.yml
  include_tasks: github-repos.yml
  include_tasks: python-tools.yml
  include_tasks: gem-tools.yml