---
- name: Install PowerShell on Debian-based systems
  hosts: all
  become: true
  tasks:

    - name: Update the list of packages
      apt:
        update_cache: yes
      tags: update

    - name: Install pre-requisite packages
      apt:
        name: wget
        state: present
      tags: install

    - name: Download the PowerShell package file
      get_url:
        url: https://github.com/PowerShell/PowerShell/releases/download/v7.4.2/powershell_7.4.2-1.deb_amd64.deb
        dest: /tmp/powershell_7.4.2-1.deb_amd64.deb
      tags: download

    - name: Install the PowerShell package
      apt:
        deb: /tmp/powershell_7.4.2-1.deb_amd64.deb
      tags: install

    - name: Resolve missing dependencies and finish the install
      apt:
        update_cache: yes
        name: -f
        state: present
      tags: install

    - name: Delete the downloaded package file
      file:
        path: /tmp/powershell_7.4.2-1.deb_amd64.deb
        state: absent
      tags: cleanup

    - name: Gather facts
      ansible.builtin.setup:
      tags: setup

    - name: Get the username of the user running the playbook
      set_fact:
        playbook_user: "{{ ansible_env.USER }}"
      tags: setup

    - name: Detect the default shell
      command: echo $SHELL
      register: shell_path
      tags: setup

    - name: Ensure ~/.bashrc includes the GOPATH
      lineinfile:
        path: "/home/{{ playbook_user }}/.bashrc"
        line: 'export PATH=$PATH:/home/{{ playbook_user }}/go/bin'
        create: yes
        state: present
      when: shell_path.stdout == "/bin/bash" or shell_path.stdout == "/usr/bin/bash"
      tags: configure

    - name: Ensure ~/.zshrc includes the GOPATH
      lineinfile:
        path: "/home/{{ playbook_user }}/.zshrc"
        line: 'export PATH=$PATH:/home/{{ playbook_user }}/go/bin'
        create: yes
        state: present
      when: shell_path.stdout == "/bin/zsh" or shell_path.stdout == "/usr/bin/zsh"
      tags: configure

    - name: Source ~/.bashrc if bash is the default shell
      shell: source /home/{{ playbook_user }}/.bashrc
      args:
        executable: /bin/bash
      when: shell_path.stdout == "/bin/bash" or shell_path.stdout == "/usr/bin/bash"
      tags: configure

    - name: Source ~/.zshrc if zsh is the default shell
      shell: source /home/{{ playbook_user }}/.zshrc
      args:
        executable: /bin/zsh
      when: shell_path.stdout == "/bin/zsh" or shell_path.stdout == "/usr/bin/zsh"
      tags: configure

    - name: Start PowerShell
      command: pwsh
      async: 10
      poll: 0
      ignore_errors: true
      tags: run
