---
- name: Install PowerShell on Debian-based systems
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: Update the list of packages
      apt:
        update_cache: yes
      tags: update
  
    - name: Download the PowerShell package file
      get_url:
        url: https://github.com/PowerShell/PowerShell/releases/download/v7.4.2/powershell_7.4.2-1.deb_amd64.deb
        dest: /tmp/powershell_7.4.2-1.deb_amd64.deb
      tags: download

    - name: Install the PowerShell package
      apt:
        deb: /tmp/powershell_7.4.2-1.deb_amd64.deb
      tags: install

    - name: Resolve missing dependencies and finish the install
      apt:
        update_cache: yes
        name: -f
        state: present
      tags: install

    - name: Delete the downloaded package file
      file:
        path: /tmp/powershell_7.4.2-1.deb_amd64.deb
        state: absent
      tags: cleanup

    - name: Start PowerShell
      command: echo "pwsh was installed" > /tmp/pwsh.txt
      async: 10
      poll: 0
      ignore_errors: true
      tags: run
