- name: "Check if BurpSuiteCA.der exists"
  stat:
    path: /usr/local/share/ca-certificates/BurpSuiteCA.der
  register: burp_cert
  
- name: Ensure expect is installed
  apt:
    name: expect
    state: present
  become: true

- name: Create expect script to run Burp Suite
  copy:
    content: |
      #!/usr/bin/expect -f
      set timeout 30
      spawn /usr/lib/jvm/jdk-22-oracle-x64/bin/java -Djava.awt.headless=true -jar /usr/share/burpsuite/burpsuite.jar
      expect "terms and conditions" {
          send "y\r"
      }
      expect eof
    dest: /tmp/run_burpsuite.exp
    mode: '0755'
  become: true

- name: Run Burp Suite with expect script and timeout
  shell: /tmp/run_burpsuite.exp
  async: 45
  poll: 0
  become: true
  become_method: sudo

- name: Wait for 30 seconds before downloading burp certificate
  wait_for:
    timeout: 30

- name: Execute curl command to download certificate
  shell: curl http://localhost:8080/cert -o /tmp/cacert.der
  become: true
  become_method: sudo
  when: burp_cert.stat.exists == False

- name: "Copying CA Certificate to /usr/local/share/ca-certificates"
  copy:
    src: /tmp/cacert.der
    dest: /usr/local/share/ca-certificates/BurpSuiteCA.der
    owner: root
    group: root
    mode: 0644
  become: true
  become_method: sudo
  when: burp_cert.stat.exists == False

- name: Create directory for Burp Suite extras
  ansible.builtin.file:
    path: "{{ burpsuite_extras_dir }}"
    state: directory
    mode: '0755'
  become: true
  become_method: sudo

- name: Download jar files
  ansible.builtin.get_url:
    url: "{{ item.value.url }}"
    dest: "{{ burpsuite_extras_dir }}/{{ item.value.jar }}"
    checksum: "{{ item.value.checksum }}"
    mode: '0644'
  become: true
  become_method: sudo
  loop: "{{ lookup('dict', burpsuite_extras_jars) }}"

- name: Ensure .BurpSuite directory exists
  file:
    path: "/home/{{ ansible_user_id }}/.BurpSuite"
    state: directory
    mode: '0755'
  ignore_errors: true
  
- name: Copy BurpSuite Community Config
  template:
    src: "templates/UserConfigCommunity.json.j2"
    dest: "/home/{{ ansible_user_id }}/.BurpSuite/UserConfigCommunity.json"

