---
- name: Configure python environment
  hosts: localhost
  become: true
  become_user: root
  tasks:
    - name: Rename EXTERNALLY-MANAGED to EXTERNALLY-MANAGED.bak
      command: mv /usr/lib/python3.11/EXTERNALLY-MANAGED /usr/lib/python3.11/EXTERNALLY-MANAGED.bak
      args:
        removes: /usr/lib/python3.11/EXTERNALLY-MANAGED
        creates: /usr/lib/python3.11/EXTERNALLY-MANAGED.bak